"""sync_model_with_db

Revision ID: 31597c7e5f22
Revises: d103adc0cb6b
Create Date: 2025-12-17 12:17:56.716656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31597c7e5f22'
down_revision = 'd103adc0cb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('chat_messages', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False)
    #     batch_op.drop_index(batch_op.f('idx_chat_messages_user_date'))

    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        # batch_op.alter_column('id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(length=36),
        #        existing_nullable=False,
        #        existing_server_default=sa.text('gen_random_uuid()'))
        # batch_op.alter_column('user_id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(length=36),
        #        existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subscription_auth',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        
        # Indexes/Keys - Commenting out potentially risky drops/creates unless I'm sure
        # batch_op.drop_constraint(batch_op.f('device_tokens_token_key'), type_='unique')
        # batch_op.drop_index(batch_op.f('idx_device_tokens_token'))
        # batch_op.drop_index(batch_op.f('idx_device_tokens_user_id'))
        # batch_op.create_index(batch_op.f('ix_device_tokens_token'), ['token'], unique=True)
        # batch_op.drop_constraint(batch_op.f('device_tokens_user_id_fkey'), type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
