"""add phone to user

Revision ID: 661fb4bce03a
Revises: eaaf8bb52da4
Create Date: 2025-12-15 13:41:03.905891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661fb4bce03a'
down_revision = 'eaaf8bb52da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('chat_messages', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False)
    #     batch_op.drop_index(batch_op.f('idx_chat_messages_user_date'))

    # with op.batch_alter_table('device_tokens', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False)
    #     batch_op.drop_constraint(batch_op.f('device_tokens_token_key'), type_='unique')
    #     batch_op.drop_index(batch_op.f('idx_device_tokens_token'))
    #     batch_op.drop_index(batch_op.f('idx_device_tokens_user_id'))
    #     batch_op.create_index(batch_op.f('ix_device_tokens_token'), ['token'], unique=True)
    #     batch_op.drop_constraint(batch_op.f('device_tokens_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
    #     # batch_op.drop_column('subscription_p256dh')
    #     # batch_op.drop_column('subscription_endpoint')
    #     # batch_op.drop_column('subscription_auth')
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_auth', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_endpoint', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_p256dh', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('device_tokens_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_device_tokens_token'))
        batch_op.create_index(batch_op.f('idx_device_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_device_tokens_token'), ['token'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('device_tokens_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chat_messages_user_date'), ['user_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    # ### end Alembic commands ###
