"""add phone to user

Revision ID: 72de94781a8a
Revises: eaaf8bb52da4
Create Date: 2025-12-15 13:43:06.736831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72de94781a8a'
down_revision = 'eaaf8bb52da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
