"""Sync migrations

Revision ID: 8b207f7f9d63
Revises: 
Create Date: 2025-12-10 12:18:59.342162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b207f7f9d63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=postgresql.ENUM('workout', 'nutrition', 'consistency', 'milestone', 'social', name='achievement_categories'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_achievements_category'))
        batch_op.drop_index(batch_op.f('ix_achievements_code'))
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_column('rarity')
        batch_op.drop_column('created_at')
        batch_op.drop_column('xp_reward')

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_body_metrics_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_body_metrics_user_recorded'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('diet_plans', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_diet_plan_user_active'))
        batch_op.drop_index(batch_op.f('ix_diet_plans_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_diet_plans_is_active'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('diet_preferences', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=postgresql.ENUM('emagrecimento', 'ganho_massa', 'manutencao', 'saude', name='diet_goals'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('budget',
               existing_type=postgresql.ENUM('ate_300', '300_500', '500_800', 'acima_800', name='budget_ranges'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('ingredient_access',
               existing_type=postgresql.ENUM('basicos', 'intermediarios', 'sofisticados', name='ingredient_access_levels'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('cooks_at_home',
               existing_type=postgresql.ENUM('sim_todas', 'as_vezes', 'raramente', 'nao', name='cooking_frequency'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('prep_time',
               existing_type=postgresql.ENUM('menos_15', '15_30', '30_60', 'mais_60', name='prep_time_ranges'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('macro_goals')

    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('weight', 'workout_frequency', 'streak', 'strength', 'custom', name='goal_types'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('active', 'completed', 'failed', 'cancelled', name='goal_statuses'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_goal_user_status'))
        batch_op.drop_index(batch_op.f('ix_goals_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('hydration_goals', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('hydration_goals_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_hydration_goals_is_active'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('hydration_logs', schema=None) as batch_op:
        batch_op.alter_column('logged_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_hydration_logs_logged_at'))
        batch_op.drop_index(batch_op.f('ix_hydration_user_logged'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('drink_type')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=postgresql.ENUM('cafe', 'almoco', 'lanche', 'jantar', 'ceia', name='meal_types'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_meal_user_consumed'))
        batch_op.drop_index(batch_op.f('ix_meal_user_type_date'))
        batch_op.drop_index(batch_op.f('ix_meals_consumed_at'))
        batch_op.drop_column('sugar_g')
        batch_op.drop_column('portion_size')
        batch_op.drop_column('sodium_mg')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('meal_rating')
        batch_op.drop_column('portion_unit')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=postgresql.ENUM('monthly', 'quarterly', 'yearly', name='subscription_plans'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('active', 'cancelled', 'past_due', 'expired', name='subscription_statuses_sub'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_subscription_user_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_subscription_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('price_paid')
        batch_op.drop_column('currency')
        batch_op.drop_column('auto_renew')

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.alter_column('unlocked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))
        batch_op.drop_constraint(batch_op.f('unique_user_achievement'), type_='unique')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender_types'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('activity_level',
               existing_type=postgresql.ENUM('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_levels'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fitness_goal',
               existing_type=postgresql.ENUM('lose_weight', 'gain_muscle', 'maintain', 'gain_strength', 'improve_health', name='fitness_goals'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'admin', name='user_roles'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('subscription_status',
               existing_type=postgresql.ENUM('active', 'suspended', name='subscription_statuses'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_user_active_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_role_subscription'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_subscription_status'))

    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='days_of_week'),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_workout_plan_user_active'))
        batch_op.drop_index(batch_op.f('ix_workout_plans_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_workout_plans_is_active'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('in_progress', 'paused', 'completed', 'cancelled', name='session_statuses'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_workout_session_user_completed'))
        batch_op.drop_index(batch_op.f('ix_workout_session_user_status'))
        batch_op.drop_column('difficulty_rating')
        batch_op.drop_column('completion_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('difficulty_rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_workout_session_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_user_completed'), ['user_id', 'completed_at'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('in_progress', 'paused', 'completed', 'cancelled', name='session_statuses'),
               nullable=False)

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_workout_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_plans_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_plan_user_active'), ['user_id', 'is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='days_of_week'),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_subscription_status'), ['subscription_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_subscription'), ['role', 'subscription_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_active_deleted'), ['is_active', 'deleted_at'], unique=False)
        batch_op.alter_column('subscription_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('active', 'suspended', name='subscription_statuses'),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('user', 'admin', name='user_roles'),
               nullable=False)
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('fitness_goal',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('lose_weight', 'gain_muscle', 'maintain', 'gain_strength', 'improve_health', name='fitness_goals'),
               existing_nullable=True)
        batch_op.alter_column('activity_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_levels'),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('male', 'female', 'other', name='gender_types'),
               existing_nullable=True)

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_user_achievement'), ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('unlocked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_user_status'), ['user_id', 'status'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('active', 'cancelled', 'past_due', 'expired', name='subscription_statuses_sub'),
               nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('monthly', 'quarterly', 'yearly', name='subscription_plans'),
               existing_nullable=True)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meal_rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('portion_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sugar_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_meals_consumed_at'), ['consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_user_type_date'), ['user_id', 'meal_type', 'consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_user_consumed'), ['user_id', 'consumed_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('meal_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('cafe', 'almoco', 'lanche', 'jantar', 'ceia', name='meal_types'),
               existing_nullable=True)

    with op.batch_alter_table('hydration_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_type', postgresql.ENUM('water', 'juice', 'tea', 'coffee', 'other', name='drink_types'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_hydration_user_logged'), ['user_id', 'logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hydration_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('logged_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('hydration_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_hydration_goals_is_active'), ['is_active'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('hydration_goals_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_user_status'), ['user_id', 'status'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('active', 'completed', 'failed', 'cancelled', name='goal_statuses'),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('weight', 'workout_frequency', 'streak', 'strength', 'custom', name='goal_types'),
               nullable=False)

    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('diet_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macro_goals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('prep_time',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('menos_15', '15_30', '30_60', 'mais_60', name='prep_time_ranges'),
               existing_nullable=True)
        batch_op.alter_column('cooks_at_home',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('sim_todas', 'as_vezes', 'raramente', 'nao', name='cooking_frequency'),
               existing_nullable=True)
        batch_op.alter_column('ingredient_access',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('basicos', 'intermediarios', 'sofisticados', name='ingredient_access_levels'),
               existing_nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ate_300', '300_500', '500_800', 'acima_800', name='budget_ranges'),
               existing_nullable=True)
        batch_op.alter_column('goal',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('emagrecimento', 'ganho_massa', 'manutencao', 'saude', name='diet_goals'),
               existing_nullable=True)

    with op.batch_alter_table('diet_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_diet_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_diet_plans_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_diet_plan_user_active'), ['user_id', 'is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_body_metrics_user_recorded'), ['user_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_metrics_recorded_at'), ['recorded_at'], unique=False)
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_reward', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rarity', postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='achievement_rarities'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_achievements_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_achievements_category'), ['category'], unique=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('workout', 'nutrition', 'consistency', 'milestone', 'social', name='achievement_categories'),
               nullable=False)

    # ### end Alembic commands ###
